// Single source of truth for all audio-department credits.
// Adding/removing an entry here automatically updates the credits page
// and the homepage's production-count stat.
const CREDITS = [
  { year: 2026, date: "Jun–Jul 2026", title: "The Christmas Feast", type: "Movie", location: "Hamilton, ON", company: "NE Christmas Eve Productions ULC", role: "Sound Mixer", imdb: null },
  { year: 2026, date: "May 2026", title: "Bulges", type: "TV Show", location: "Hamilton, ON", company: "Bulges Inc.", role: "Sound Mixer", imdb: null },
  { year: 2026, date: "May 2026", title: "Argos Media Day", type: "TV", location: "Waterloo, ON", company: "Superhuman Images Inc.", role: "Sound Mixer", imdb: null },
  { year: 2026, date: "May 2026", title: "Sportsnet Marketing", type: "Ad", location: "Toronto, ON", company: "Rogers Communications", role: "Sound Mixer", imdb: null },
  { year: 2026, date: "May 2026", title: "Can I Come In", type: "Movie", location: "Toronto, ON", company: "CICI Film Inc.", role: "Sound Mixer", imdb: null },
  { year: 2026, date: "Jan 2026", title: "My Highschool Sweetheart Just Died", type: "Movie", location: "Toronto, ON", company: "FCP Film Inc.", role: "Sound Mixer", imdb: null },
  { year: 2026, date: "Jul 2026", title: "Haventree Bank", type: "Ad", location: "Toronto, ON", company: "Fela Productions", role: "Sound Mixer", imdb: null },
  { year: 2026, date: "May 2026", title: "Drake — Iceman", type: "Music Video", location: "Toronto, ON", company: "Kid Studio", role: "Playback / A2", imdb: null },
  { year: 2026, date: "Mar 2026", title: "Royal Nannies", type: "Movie", location: "Hamilton, ON", company: "French Toast Films", role: "Sound Mixer", imdb: null },

  { year: 2025, date: "Sep–Oct 2025", title: "America's Culinary Cup", type: "Reality Show", location: "Etobicoke, ON", company: "Sagia Productions", role: "A2", imdb: null },
  { year: 2025, date: "May–Jun 2025", title: "Lice", type: "Movie", location: "Hamilton, ON", company: "French Toast Films", role: "Boom Operator", imdb: "tt37255755" },
  { year: 2025, date: "Oct 2025", title: "FOX Sports WS Pregame Special", type: "TV", location: "Toronto, ON", company: "FOX Sports", role: "Sound Mixer", imdb: null },
  { year: 2025, date: "Aug 2025", title: "H&S Beats Evolution Project", type: "Ad", location: "Calgary, AB", company: "Sequoia Productions", role: "Sound Mixer", imdb: null },
  { year: 2025, date: "Aug 2025", title: "Doc", type: "TV Show", location: "Hamilton, ON", company: "Idaho Productions Ltd.", role: "Daily Boom Operator", imdb: null },
  { year: 2025, date: "Jul 2025", title: "I Will Find You", type: "TV Show", location: "Toronto, ON", company: "Quartz Productions", role: "Daily Boom Operator", imdb: null },
  { year: 2025, date: "Jul 2025", title: "Killer Clues / How to Hire a Hitman", type: "TV Show", location: "Hamilton, ON", company: "Shadow Pine Productions", role: "Sound Mixer", imdb: null },
  { year: 2025, date: "May 2025", title: "Holt Renfrew X Function", type: "Ad Campaign", location: "Toronto, ON", company: "Made By Plot", role: "Sound Mixer", imdb: null },
  { year: 2025, date: "Mar–Apr 2025", title: "Silent Nights", type: "Movie", location: "Hamilton, ON", company: "Neshama Entertainment", role: "Sound Mixer", imdb: null },
  { year: 2025, date: "Jan 2025", title: "Savvy Sheldon Feels Good as Hell", type: "Movie", location: "Hamilton, ON", company: "Neshama Entertainment", role: "Boom Operator", imdb: "tt35002927" },

  { year: 2024, date: "Jun 2024", title: "Thank You Come Again", type: "Short Film", location: "Toronto, ON", company: null, role: "Sound Mixer", imdb: null },
  { year: 2024, date: "Jun–Jul 2024", title: "The Memory Keeper", type: "Movie", location: "London, ON", company: "Falsehood Pictures Inc.", role: "Sound Mixer", imdb: "tt22640460" },
  { year: 2024, date: "Aug 2024", title: "Macy Murdoch S2", type: "TV Series", location: "Toronto, ON", company: "Shaftesbury Digital III Inc.", role: "Sound Mixer", imdb: "tt27251194" },
  { year: 2024, date: "Nov 2024", title: "Dateless to Dangerous", type: "Movie", location: "Hamilton, ON", company: "Neshama Entertainment", role: "Sound Mixer", imdb: "tt34555664" },
  { year: 2024, date: "Sep 2024", title: "Maple Leafs Media Day", type: "Social", location: "Toronto, ON", company: "Superhuman Images Inc.", role: "Sound Mixer", imdb: null },
  { year: 2024, date: "Jun–Jul 2024", title: "Love Potion", type: "Movie", location: "Hamilton, ON", company: "Neshama Entertainment", role: "Sound Mixer", imdb: null },
  { year: 2024, date: "Oct 2024", title: "Food52 Episode", type: "Social", location: "St. Catharines, ON", company: "Food52", role: "Sound Mixer", imdb: null },
  { year: 2024, date: "Oct 2024", title: "One Voice, One Team", type: "Ad", location: "Brampton, ON", company: "Nexus Communications North America", role: "Sound Mixer", imdb: null },
  { year: 2024, date: "Oct 2024", title: "Gowling", type: "Ad", location: "Waterloo, ON", company: "Nexus Communications North America", role: "Sound Mixer", imdb: null },
  { year: 2024, date: "Sep 2024", title: "She Was Murdered In My House", type: null, location: "Toronto, ON", company: "Superhuman Images Inc.", role: "Boom Operator", imdb: null },
  { year: 2024, date: "Sep 2024", title: "FriendSHIP", type: "Social / Charity Ad", location: "Toronto, ON", company: "Merchant", role: "Sound Mixer", imdb: null },
  { year: 2024, date: "Sep 2024", title: "Enna Nu Rehna Sehna Nai Aunda", type: "Movie", location: "Brampton, ON", company: "Qultr Motion Pictures", role: "Sound Mixer", imdb: "tt33044546" },
  { year: 2024, date: "Aug–Sep 2024", title: "Ordinary Girl in a Tiara", type: "Movie", location: "Hamilton, ON", company: "NE OGIAT Productions ULC", role: "Boom / Mixer", imdb: "tt33362130" },
  { year: 2024, date: "Aug 2024", title: "Legacy Assets BHP", type: "Ad", location: "Elliot Lake, ON", company: "Barbershop Films", role: "Sound Mixer", imdb: null },
  { year: 2024, date: "May 2024", title: "Her Last Supper", type: "Movie", location: "Toronto, ON", company: "Her Last Supper Productions Inc.", role: "Boom Operator", imdb: "tt32056451" },
  { year: 2024, date: "Apr 2024", title: "My Husbands Mistress", type: "Movie", location: "Hamilton, ON", company: "MHM Productions Inc.", role: "Sound Mixer / Boom", imdb: "tt32048472" },
  { year: 2024, date: "Feb–Mar 2024", title: "Gentle Barbarians", type: "Movie", location: "Mississauga, ON", company: "Luna Reel Productions Inc.", role: "Sound Mixer", imdb: "tt33039641" },

  { year: 2023, date: "Nov–Dec 2023", title: "Morningside", type: "Movie", location: "Scarborough, ON", company: "Augusta Avenue Productions", role: "Sound Mixer", imdb: "tt24666718" },
  { year: 2023, date: "Oct–Nov 2023", title: "The Love Club S2", type: "Movie", location: "Hamilton, ON", company: "Nikki Ray Media", role: "Sound Mixer", imdb: "tt19896920" },
  { year: 2023, date: "Oct 2023", title: "Nissan Social", type: "Commercial", location: "Mississauga, ON", company: "Angle Media Group", role: "Sound Mixer", imdb: null },
  { year: 2023, date: "Oct 2023", title: "Frogs", type: "Short Film", location: "Warkworth, ON", company: "Molly Shears Productions", role: "Sound Mixer", imdb: null },
  { year: 2023, date: "Aug 2023", title: "Move In", type: "Short Film", location: "Markham, ON", company: "Decorum", role: "Sound Mixer", imdb: "tt28862680" },
  { year: 2023, date: "Jul 2023", title: "Homes Pro Corporate", type: "Commercial", location: "Markham, ON", company: "Libalula", role: "Sound Mixer", imdb: null },
  { year: 2023, date: "Jun 2023", title: "Revved Up Recaps", type: "Commercial", location: "Toronto, ON", company: "Spin Master Corp.", role: "Sound Mixer", imdb: null },
  { year: 2023, date: "Jun 2023", title: "How To Fall in Love at Christmas", type: "Movie", location: "Hamilton, ON", company: "CME Winter Productions Inc.", role: "Sound Mixer", imdb: "tt29144851" },
  { year: 2023, date: "May 2023", title: "Dinner Party (Working Title)", type: "Movie", location: "Toronto, ON", company: "Autograph Communications Inc.", role: "Sound Mixer", imdb: "tt31806236" },
  { year: 2023, date: "Apr–May 2023", title: "J'adore New York", type: "Movie", location: "Hamilton, ON", company: "CME Winter Productions Inc.", role: "Sound Mixer", imdb: null },
  { year: 2023, date: "Mar 2023", title: "Swept Up In Christmas", type: "Movie", location: "Hamilton, ON", company: "CME Autumn Productions Inc.", role: "Boom Operator", imdb: null },
  { year: 2023, date: "Feb 2023", title: "Subaru Customer Stories", type: "Commercial", location: "Niagara, ON", company: "Zulubot Inc.", role: "Sound Mixer", imdb: null },
  { year: 2023, date: "Jan 2023", title: "Christmas Casanova", type: "Movie", location: "Hamilton, ON", company: "CME Autumn Productions Inc.", role: "Sound Mixer", imdb: "tt27728751" },

  { year: 2022, date: "Nov 2022", title: "Giving Hope: The Ni'Cola Mitchell Story", type: "Movie", location: "Hamilton, ON", company: "CME Autumn Productions Inc.", role: "Boom Op", imdb: null },
  { year: 2022, date: "Nov 2022", title: "Sounds Black", type: "Documentary", location: "Toronto, ON", company: "CBF Productions Inc.", role: "Sound Mixer", imdb: null },
  { year: 2022, date: "Oct 2022", title: "Macy Murdoch", type: "TV Series", location: "Toronto, ON", company: "Shaftesbury Digital III Inc.", role: "Boom Operator", imdb: "tt27251194" },
  { year: 2022, date: "Oct 2022", title: "A Year In Film", type: "Documentary", location: "Toronto, ON", company: "Hollywood Suite", role: "Sound Mixer", imdb: null },
  { year: 2022, date: "Sep 2022", title: "Pawsitively Perfect", type: "Movie", location: "Hamilton, ON", company: "CME Autumn Productions Inc.", role: "Boom Operator", imdb: null },
  { year: 2022, date: "Sep 2022", title: "Pairs Well With Love", type: "Movie", location: "Hamilton, ON", company: "CME Autumn Productions Inc.", role: "Boom Operator, Sound Mixer", imdb: null },
  { year: 2022, date: "Aug 2022", title: "Warrior Strong", type: "Movie", location: "Sault Ste-Marie, ON", company: "Darius-Warrior Productions Inc.", role: "Boom Operator, Sound Mixer", imdb: null },
  { year: 2022, date: "Aug 2022", title: "One In A Million", type: "Movie", location: "Hamilton, ON", company: "CME Autumn Productions Inc.", role: "Boom Operator", imdb: null },
  { year: 2022, date: "May & Aug 2022", title: "The Love Club 1/2/4", type: "Movie", location: "Hamilton, ON", company: "CME Autumn Productions Inc.", role: "Boom Operator", imdb: "tt19896920" },
  { year: 2022, date: "Jul 2022", title: "Royally In Love", type: "Movie", location: "Toronto, ON", company: "CME Autumn Productions Inc.", role: "Boom Operator", imdb: null },
  { year: 2022, date: "Mar 2022", title: "Christmas On The Rocks", type: "Movie", location: "Toronto, ON", company: "CME Autumn Productions Inc.", role: "Boom Operator", imdb: "tt23873758" },
  { year: 2022, date: "May 2022", title: "Wedding Wars", type: "Movie", location: "Toronto, ON", company: "CME Autumn Productions Inc.", role: "Boom Operator", imdb: null },
  { year: 2022, date: "Mar 2022", title: "Fashionably Date", type: "Movie", location: "Toronto, ON", company: "CME Autumn Productions Inc.", role: "Boom Operator", imdb: null },
  { year: 2022, date: "Mar 2022", title: "The Christmas Switch", type: "Movie", location: "Toronto, ON", company: "CME Autumn Productions Inc.", role: "Boom Operator", imdb: null },
  { year: 2022, date: "Mar 2022", title: "Luck Strikes In Winter", type: "Movie", location: "Hamilton, ON", company: "CME Autumn Productions Inc.", role: "Boom Operator", imdb: null },

  { year: 2021, date: "Jan–Mar 2020, Oct–Nov 2021", title: "Santa Claus The Serial Killer", type: "BBC Doc", location: "GTA, ON", company: "Forest (We Are Forest) Productions", role: "Boom Op", imdb: "tt16587970" },
  { year: 2021, date: "Sep 2021", title: "Ted X", type: "Ted X Web Special", location: "Toronto, ON", company: "Toronto Sound", role: "Sound Mixer", imdb: null },
  { year: 2021, date: "Aug 2021", title: "Most of the Time We Are Just Waiting!", type: "Movie", location: "Toronto, ON", company: "Molly Shears Productions", role: "Mixer", imdb: "tt18936270" },
  { year: 2021, date: "Jul 2021", title: "To Do List", type: "Commercial", location: "Toronto, ON", company: "Brand New School", role: "Boom Operator", imdb: null },
  { year: 2021, date: "Apr / Nov 2021", title: "Imposters Sin Room", type: "Short Film", location: "Toronto, ON", company: "AKA Films", role: "Audio Mixer", imdb: null },

  { year: 2020, date: "Sep 2020", title: "Topline", type: "CBC TV Show", location: "Toronto, ON", company: "Shaftesbury Digital III Inc.", role: "Boom Operator", imdb: "tt16390628" },

  { year: 2019, date: "Jul 2019", title: "Middle of Nowhere", type: "Short Film", location: "Tobermory, ON", company: "Molly Shears Productions", role: "Audio Mixer", imdb: "tt11095494" },

  { year: 2018, date: "Jun–Aug 2018", title: "Carrots", type: "Short Film", location: "Toronto, ON", company: "Molly Shears Productions", role: "Lead Audio Engineer, Boom Op", imdb: "tt9733168" },

  { year: 2017, date: "2015–2017", title: "Survivor (US Series)", type: "Dream Team", location: "Cambodia, Fiji", company: "SEG", role: "Audio Assist", imdb: "tt0239195" },

  { year: 2016, date: "Sep 2016", title: "Scotiabank - Heroes of Hockey Day", type: "Commercial", location: "Brampton, ON", company: "The Mark Studios", role: "A2", imdb: null }
];
